import { Glob } from "bun";
import { readFileSync } from "node:fs";
import { join, sep } from "node:path";
import { stringify } from "yaml";

import { usageError } from "./errors.ts";
import { parseFrontmatter, type Frontmatter } from "./frontmatter.ts";

export type DocRecord = {
  path: string; // posix, relative to the scan root
  type: string;
  title: string;
  description?: string;
  when?: string;
  timestamp?: string;
  tags?: string[];
  data?: Frontmatter; // the doc's raw frontmatter, dumped verbatim into the index
};

// Build/VCS noise we never want in a knowledge index.
const IGNORED_SEGMENTS = new Set([
  "node_modules",
  ".git",
  "dist",
  "build",
  "coverage",
  ".scratch",
  ".next",
  ".claw", // daemon state, never a concept
]);

// OKF reserves these filenames; they are structure, not concepts.
const RESERVED = new Set(["index.md", "log.md"]);

export const BLOCK_START = "<!-- claw:index -->";
export const BLOCK_END = "<!-- /claw:index -->";

// Where installed/active skills live — the skill mechanism's territory. These
// are the only two; claw indexes nothing under them.
const SKILL_ROOTS = [".agents/skills/", ".claude/skills/"];

export function scanDocs(root: string): DocRecord[] {
  const records: DocRecord[] = [];

  for (const rel of listMarkdown(root)) {
    if (SKILL_ROOTS.some((dir) => rel.startsWith(dir))) continue;
    const base = rel.split("/").pop() ?? "";
    if (RESERVED.has(base)) continue;

    let text: string;
    try {
      text = readFileSync(join(root, rel), "utf8");
    } catch {
      continue;
    }

    // Only frontmatter-bearing docs are OKF concepts. Plain files (README,
    // AGENTS.md, notes) are not indexed — which also keeps a pointer-block host
    // file from listing itself.
    const parsed = parseFrontmatter(text);
    if (!parsed.hasFrontmatter) continue;

    records.push(toRecord(rel, parsed.data));
  }

  records.sort((a, b) => a.path.localeCompare(b.path));
  return records;
}

// Enumerate candidate markdown as posix paths relative to root. In a git repo
// this is the authoritative `.gitignore`-respecting set (tracked + untracked,
// minus ignored); the daemon's coarse watch ignore never has to be exact. Falls
// back to a glob with a hardcoded ignore list outside a repo.
function listMarkdown(root: string): string[] {
  const git = Bun.spawnSync(
    [
      "git",
      "-C",
      root,
      "ls-files",
      "--cached",
      "--others",
      "--exclude-standard",
      "-z",
      "--",
      "*.md",
    ],
    { stderr: "ignore" },
  );
  if (git.exitCode === 0) {
    return [...new Set(git.stdout.toString().split("\0").filter(Boolean))];
  }

  const glob = new Glob("**/*.md");
  return [...glob.scanSync({ cwd: root, dot: true, onlyFiles: true })]
    .filter((rel) => !rel.split(sep).some((segment) => IGNORED_SEGMENTS.has(segment)))
    .map((rel) => rel.split(sep).join("/"));
}

function toRecord(path: string, data: Frontmatter): DocRecord {
  return {
    path,
    type: asString(data.type) ?? "Untyped",
    title: asString(data.title) ?? deriveTitle(path),
    description: asString(data.description),
    when: asString(data.when),
    timestamp: asString(data.timestamp),
    tags: Array.isArray(data.tags) ? data.tags.map((tag) => String(tag)) : undefined,
    data,
  };
}

function asString(value: unknown): string | undefined {
  if (typeof value === "string") return value.trim() || undefined;
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (value instanceof Date) return value.toISOString();
  return undefined;
}

function deriveTitle(path: string): string {
  const base = (path.split("/").pop() ?? path).replace(/\.md$/, "");
  return base
    .split(/[-_]+/)
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

// The index is a YAML list — one entry per concept, `file` plus the doc's
// frontmatter verbatim. Plain data: readable, ordered, trivially parsed.
export function buildIndex(docs: DocRecord[]): string {
  return stringify(docs.map((doc) => ({ file: `./${doc.path}`, ...doc.data })));
}

// The default injection: a static prompt pointing the agent at index.yaml. It
// never changes as docs change — no churn in an always-loaded file.
export function referenceBlock(indexPath = "index.yaml"): string {
  return [
    BLOCK_START,
    "<!-- Generated by `claw index`. -->",
    `The documents in this workspace are indexed in \`./${indexPath}\` — one entry`,
    "per doc, with its path and frontmatter (type, description, `when`, …). Read",
    "it to discover what docs exist and when to consult them.",
    BLOCK_END,
  ].join("\n");
}

// The opt-in injection: the full index.yaml content, fenced so a markdown
// formatter leaves the embedded YAML alone. Ambient but grows with the corpus.
export function inlineBlock(docs: DocRecord[]): string {
  return [
    BLOCK_START,
    "<!-- Generated by `claw index`. Edit the docs, not this block. -->",
    "```yaml",
    buildIndex(docs).trimEnd(),
    "```",
    BLOCK_END,
  ].join("\n");
}

export function injectManagedBlock(content: string, block: string): string {
  const start = content.indexOf(BLOCK_START);
  const end = content.indexOf(BLOCK_END);

  if (start !== -1 && end !== -1 && end > start) {
    return content.slice(0, start) + block + content.slice(end + BLOCK_END.length);
  }

  // A lone or out-of-order marker means a corrupted block. Appending another
  // would compound the damage — refuse and let the user fix it.
  if (start !== -1 || end !== -1) {
    throw usageError("Refusing to update: unbalanced claw:index markers in the target file.", {
      hint: "Remove the stray <!-- claw:index --> / <!-- /claw:index --> marker, then re-run.",
    });
  }

  if (content.length === 0) return block + "\n";
  const gap = content.endsWith("\n\n") ? "" : content.endsWith("\n") ? "\n" : "\n\n";
  return content + gap + block + "\n";
}
